POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"kiliadsds",
    "password": "cc"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"Kyless",
    "password": "ccoucou"
}
### bon mot de passe
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Kyles",
    "password": "cc"
}

### Mauvais mot de passe
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Kyles",
    "password": "ccc"
}


### Test le token est correct expirée ici
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt5bGVzIiwiaWF0IjoxNjQ1NzY5NjQ5LCJleHAiOjE2NDU3Njk3MDl9.DPpm5qWqHA2d-wUkByYuAo9VVGI3R_eUCvw84zOlcLI

### Test le token est incorrect 
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer salut

###
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt5bGVzIiwiaWF0IjoxNjQ1NzA3OTA0LCJleHAiOjE2NDU3MDc5NjR9.DMPkxakAj7d6qc8y_qjHQ3cCWDowm9r7ubOW6UJ3ne8
###
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"Nicky",
    "password": "ccoucou"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Nicky",
    "password": "ccoucou"
}


### RefreshToken test 
POST http://localhost:3000/auth/refreshToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiTmlja3kiLCJpYXQiOjE2NDU3NzI2NzAsImV4cCI6MTY3NzMzMDI3MH0.rc7kODyJI7vGgfJSGF3I4m35FrPpfQ8sRs2iLi3d_do


### Test new accessToken
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDU3NzI2ODEsImV4cCI6MTY0NTc3Mjc0MX0.Z4KOL8kOaPG_NsORleynwnf4Rt9O5X8zIfJ91l2kq1k
###