POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"Michel",
    "password": "mcihelpassword"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"Kyles",
    "password": "coucou"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Kyles",
    "password": "coucou"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Michel",
    "password": "mcihelpassword"
}
### bas token
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer salut

###
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"Nicky",
    "password": "ccoucou"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Nicky",
    "password": "ccoucou"
}



### Test new accessToken
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiI1MTlhMmQwMy00OWY0LTQwNjUtYjdkMS00MDRmYzMzMWNlNzMiLCJpYXQiOjE2NDY4Mjg0OTksImV4cCI6MTY3ODM4NjA5OX0.2f0Xfw1sUtBnFjRf-fiE1Aw3x21b4ggu4MUc8Rx--ZQ
###

GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiIwNjk3OTNkOC1mY2Q3LTRjZWUtYjkyZC0yYjc3ZGQ1OTgwMjQiLCJpYXQiOjE2NDY4MjkxODQsImV4cCI6MTY3ODM4Njc4NH0.3XqjUVSSHXTVMU5mzsS6S5CbH3tOF3Ecnf4hPtyOXqU
### Test refreshToken
POST http://localhost:3000/auth/refreshToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX3V1aWQiOiJjZTlkNDIzMy1hN2ZmLTQ1YTYtYjkzMy02NjJjNTNhNzE5MzUiLCJpYXQiOjE2NDY4Mjg2NjYsImV4cCI6MTY3ODM4NjI2Nn0.NmsVzH4comusuMsUXhWd4v2dReLzUus3VsD4Uj9RHLw

