POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"kiliadsdsdsrer",
    "password": "cc"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"Kyless",
    "password": "ccoucou"
}
### bon mot de passe
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"kiliadsdsdsrer",
    "password": "cc"
}

### Mauvais mot de passe
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Kyles",
    "password": "ccc"
}


### Test le token est correct expirée ici
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt5bGVzIiwiaWF0IjoxNjQ1NzY5NjQ5LCJleHAiOjE2NDU3Njk3MDl9.DPpm5qWqHA2d-wUkByYuAo9VVGI3R_eUCvw84zOlcLI

### Test le token est incorrect 
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer salut

###
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikt5bGVzIiwiaWF0IjoxNjQ1NzA3OTA0LCJleHAiOjE2NDU3MDc5NjR9.DMPkxakAj7d6qc8y_qjHQ3cCWDowm9r7ubOW6UJ3ne8
###
POST http://localhost:3000/auth/register
Content-Type: application/json 

{
    "username":"Nicky",
    "password": "ccoucou"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json 

{
    "username":"Nicky",
    "password": "ccoucou"
}


### RefreshToken test 
POST http://localhost:3000/auth/refreshToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoia2lsaWFkc2RzZHNyZXIiLCJpYXQiOjE2NDY3MjgxODUsImV4cCI6MTY3ODI4NTc4NX0.24P6363PLgvOV-jC2-Nh69hr91pJ13ioj-ksJ24lMjE


### Test new accessToken
GET http://localhost:3000/auth/validateToken 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoia2lsaWFkc2RzZHNyZXIiLCJpYXQiOjE2NDY3MjgwOTEsImV4cCI6MTY3ODI4NTY5MX0.nNzloNZ8cEAYrLWuDaXxWLVqzvONrgOmimrOOPU650o
###

