GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY0NTQ1NDc1NH0.pUpfcaSjnsn2lZw6xFWZTfjnrAq3W3L6c4IRBMGfPkI
###
DELETE http:localhost:3000/logout 
Content-Type: application/json
###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY0NTUxNzgwM30._UszvkczxLT5Ln6Eik2KI3udT83D0EUNWdRkh8gOwqI"
}
###
POST http://localhost:3000/login 
Content-Type: application/json 

{
    "username":"Kyle"
}