export const theme: { [key: string]: string } = {
  normal: 'bg-[#A4ACAF]',
  fighting: 'bg-[#D56723]',
  flying: 'bg-[#EAEAEA]',
  poison: 'bg-[#B97FC9]',
  ground: 'bg-[#F7DE3F]',
  rock: 'bg-[#A38C21]',
  bug: 'bg-[#729F3F]',
  ghost: 'bg-[#7B62A3]',
  stell: 'bg-[#9EB7B8]',
  fire: 'bg-[#FD7D24]',
  grass: 'bg-[#9bcc50]',
  psychic: 'bg-[#F366B9]',
  ice: 'bg-[#51C4E7]',
  dragon: 'bg-[#3923a3]',
  dark: 'bg-[#707070]',
  fairy: 'bg-[#FDB9E9]',
  unknown: '',
  shadow: 'bg-[#7B62A3]',
  water: 'bg-[#4592C4]',
}
export const imageTheme: { [key: string]: string } = {
  normal: 'bg-gradient-to-r from-[#A4ACAF] to-[#FFFFFF]',
  fighting: 'bg-gradient-to-r from-[#D56723]  to-[#FFFFFF]',
  flying: 'bg-gradient-to-r from-[#EAEAEA] to-[#FFFFFF]',
  poison: 'bg-gradient-to-r from-[#B97FC9] to-[#FFFFFF]',
  ground: 'bg-gradient-to-r from-[#F7DE3F] to-[#FFFFFF]',
  rock: 'bg-gradient-to-r from-[#A38C21] to-[#FFFFFF]',
  bug: 'bg-gradient-to-r from-[#729F3F] to-[#FFFFFF]',
  ghost: 'bg-gradient-to-r from-[#7B62A3] to-[#FFFFFF]',
  stell: 'bg-gradient-to-r from-[#9EB7B8] to-[#FFFFFF]',
  fire: 'bg-gradient-to-r from-[#FD7D24] to-[#FFFFFF]',
  grass: 'bg-gradient-to-r from-[#9bcc50] to-[#FFFFFF]',
  psychic: 'bg-gradient-to-r from-[#F366B9] to-[#FFFFFF]',
  ice: 'bg-gradient-to-r from-[#51C4E7] to-[#FFFFFF]',
  dragon: 'bg-gradient-to-r from-[#3923a3] to-[#FFFFFF]',
  dark: 'bg-gradient-to-r from-[#707070] to-[#FFFFFF]',
  fairy: 'bg-gradient-to-r from-[#FDB9E9] to-[#FFFFFF]',
  unknown: '',
  shadow: 'bg-gradient-to-r from-[#7B62A3] to-[#FFFFFF]',
  water: 'bg-gradient-to-r from-[#4592C4] to-[#FFFFFF]',
}
